---

  # To get below to work, add --extra-vars "new_password=abcd" when invoking
  # the playbook

  # - name: Change password for root user
  #   user:
  #     name: "{{ ansible_user }}"
  #     password: "{{ new_password | password_hash('sha512') }}"
  #     update_password: always

# ref: https://ryaneschinger.com/blog/securing-a-server-with-ansible/

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: restart ssh

- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: restart ssh
